In [90]:
print("hello we are going to learn numpy")

hello we are going to learn numpy


In [9]:
import numpy as np
a=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [5,4,3,2,1],
])

s=[j*2 for j in a]
s


[array([ 2,  4,  6,  8, 10]),
 array([12, 14, 16, 18, 20]),
 array([10,  8,  6,  4,  2])]

In [79]:
import numpy as np
s=[]
j=[]
aa=np.array([1,2,0,4],dtype=bool)
b=np.array([5,6,7,8])

s.append(aa+b)
s
j.append(aa-b)

k=aa*b
k

array([5, 6, 0, 8])

In [87]:
aa=np.array([1,2,3,4])
mm=list(map(lambda x:x*x,aa))#lambda function to get sequential array
mm

[1, 4, 9, 16]

In [88]:
#now adding substracting and multiplaying the array
w=np.array([1,2,3,4])
x=np.array([5,3,8,9])
sum=w+x
sub=w-x
mul=w*x
div=w/x

total=sum+sub+mul+div
total.dtype



dtype('float64')

In [71]:
#going to the datatype
#string , integer , float , boolean 
a=np.array([
    [1,0,1,0,0],
    [0,0,1,1,1],
    [1,1,1,1,0],
],dtype=bool)

b=np.array([
    [0,0,1,0,1],
    [1,0,0,1,0],
    [1,0,1,0,0],
],dtype=bool)

sum=a+b
sum

#finding the datatype of matrix

z=np.array([True,False,True])
print(z.dtype)
c=np.array([3,4,5,6])
print(c.dtype)
f=np.array([1.1,456,2.34])
print(f.dtype)
e=np.array(["hello","hi","welcome"])
print(e.dtype)

bool
int32
float64
<U7


In [72]:
#reading file
a=open("s.txt",'r')
s=a.read()
s


'hello'

In [66]:
#now printing dimensional of array

q=np.array([1,2,3])
print(q.ndim)
z=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
])
print(z.ndim)



1
2


In [93]:
#showing the sizes of array
qx=np.array([
    [1,2,3],
    [4,5,6],
])
print(qx.size)#this is used to find out the number of element

6


In [100]:
#Now exploring the arranging the matrix
bv=np.arange(1,45,2)#arange function is generating sequences of whole numbers with start, end , step arguments
vv=np.arange(1,10,2)#project to show the even number
ff=np.array(1,10)#project to show the odd number
print(vv)

[1 3 5 7 9]


In [101]:
#NOw lets enjoy to find the row and columns of given matrix

mat=np.array([
    [1,2,3,4],
    [4,5,6,7],
])
mat2=np.array([
    [1,2,3,4],
    [4,5,6,7],
    [2,3,4,5],
])
print(mat.shape,mat2.shape)#shape classes uses to finf the given matrix number of rows and column

(2, 4) (3, 4)


In [114]:
#lets use the function of different matrix for generating the matrix
zz=np.ones(6)#ones matrix gives us 1 matrix which means True
print(z)
#lets give it to dimensional 

z=np.ones((3,2))#we are passing three rows and two columns in tuples
print(z.dtype,'\n',z)

#lets create simple projects

#now
row=int(input("enter the number of rows: "))
column=int(input("enter the number of columns: "))
dtype=input("enter the data type: ")
one_matrix=np.ones((row,column),dtype=dtype)
print(one_matrix)
#project completed 

#================ Now are moving to the next==============
#Now we are exploring zeros matrix

zero=np.zeros(6)
print(zero)
z=np.zeros((4,3))#we are passing three rows and two columns in tuples
print(z.dtype,'\n',z)

#lets create again same simple projects

#now
row=int(input("enter the number of rows: "))
column=int(input("enter the number of columns: "))
dtype=input("enter the data type: ")
zero_matrix=np.zeros((row,column),dtype=dtype)
print(zero_matrix)
#project completed 



[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
enter the number of rows: 3
enter the number of columns: 4
enter the data type: int
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[0. 0. 0. 0. 0. 0.]
float64 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
enter the number of rows: 23
enter the number of columns: 45
enter the data type: int
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [124]:
# lest's generate the the random values and make a beautiful matrix

#let's start

nm=np.empty(2)#empty function genrated us random value and carete a array

print(nm)

#lets nake simple project
row=int(input("enter the number of rows: "))
column=int(input("enter the number of columns: "))
dtype=input("enter the data type: ")
empty_matrix=np.zeros((row,column),dtype=dtype)
print(empty_matrix)


[2.12199579e-313 9.33678148e-313]
enter the number of rows: 4
enter the number of columns: 5
enter the data type: float
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [130]:
#Doing the sum of matrix in standard way
su=np.array([3,4,2,1])
bu=np.array([6,7,8,9])
sum=np.sum([su,bu])#it takes paramter in list but not support tuple
print(sum)

#lets print sum of matrix only rows
sum1=np.sum([su,bu],axis=0)#0 means column
sum2=np.sum([su,bu],axis=1)# 1 means rows
print(sum1,sum2)

40
[ 9 11 10 10] [10 30]


In [61]:
#================Adavnced Functions=================
#let's explore the advanced function of numpy
#ravel(), transpose(), reshape(), linspace(), flatten()
import numpy as np
#1. reshape() # it is a function used to make shape of array in rows and column
#example
qx=np.array([1,2,3,4,5,6])# we have the the six elements
print(qx.size)# we have size
# reshape(row,column) #it takes two arguments
shape=qx.reshape(3,2)#its only support the valid shape if there is element then it only reshape by its conditon
print(shape)

#project
data=np.arange(20,50,2)#genrating the sequences of numbers
print(data.size)# The size is seventeen
#note plz give valid shape other wise it throws error
row=int(input("enter the number of rows: "))
column=int(input("enter the number of columns: "))

shape1=data.reshape(row,column)
print(shape1)
print("hello")

#ravel() function and flatten() function  both are same
#it is used to change multi-dimensional array onto one dimensional 1d
xx=np.array([
    [1,2,3,4],
    [4,3,2,4],
    [9,6,8,5],
],dtype=int,order='C')#order is used to show style of matrix F and C 
print(xx)
print(xx.shape)

#now chaging into onedimensional
rav=xx.ravel()
print(rav)
flat=xx.flatten() # or we can use flat also
print(flat)

#Now it's times for transpose
ds=np.array([
    [4,3,2],
    [1,2,3],
])
print(ds.transpose())# transpose is used to transpose the matrix

# last and important is linspace
#it is float and optional
#(start, end, num=True, retstep=True)#retstep show us spaces 
#there is start and end num will give us how many number generated 
# it shows us float result 
z=np.linspace(1,100,num=5)#num=how many number to show
print(z)
zz=np.linspace(0.2,50.08,num=7,retstep=True)
print(zz)
print(z)
zzz=np.linspace(1,10,num=5,retstep=True,endpoint=False)#if i dont want include last value then we should use endpoint=False
#retstep shows us the step of number or common difference
print(zzz)

#let's do project
start=int(input("enter starting value: "))
end=int(input("enter end value: "))
num=int(input("enter how many number to show: "))
retstep=input("Enter True or Flase for common difference: ")
endpoint=input("Do you want to see endpoint if yes:True or Flase: ")
dtype=input("enter int,float optional: ")
lin=np.linspace(start,end,num=num,dtype=dtype,retstep=retstep,endpoint=endpoint)
print(lin)


6
[[1 2]
 [3 4]
 [5 6]]
15
enter the number of rows: 3
enter the number of columns: 5
[[20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]
hello
[[1 2 3 4]
 [4 3 2 4]
 [9 6 8 5]]
(3, 4)
[1 2 3 4 4 3 2 4 9 6 8 5]
[1 2 3 4 4 3 2 4 9 6 8 5]
[[4 1]
 [3 2]
 [2 3]]
[  1.    25.75  50.5   75.25 100.  ]
(array([ 0.2       ,  8.51333333, 16.82666667, 25.14      , 33.45333333,
       41.76666667, 50.08      ]), 8.313333333333333)
[  1.    25.75  50.5   75.25 100.  ]
(array([1. , 2.8, 4.6, 6.4, 8.2]), 1.8)
enter starting value: 1
enter end value: 10
enter how many number to show: 3
Enter True or Flase for common difference: True
Do you want to see endpoint if yes:True or Flase: True
enter int,float optional: int
(array([ 1,  5, 10]), 4.5)


In [115]:
#we are going to learn airthmetic function

import numpy as np
a=np.array([1,2,4,6,7,8])
b=np.array([6,7,4,2,6,9])

sum=np.add(a,b)
print(sum)
sub=np.subtract(a,b)
print(sub)

mul=np.multiply(a,b)
print(mul)

div=np.divide(a,b)
print(div)

#Applying the power function
power=np.power(a,2)#here it takes two argument (array_value,Times)
print(power)

#now remainder and mod
#let's create our own array
v=np.array([2,4,6,9])
vv=np.array([1,2,3,4])
mod=np.mod(v,vv)
print(mod)

remainder=np.remainder(v,vv)
print(remainder)

#angle and conjucative
conjj=np.array([12-4j])
con=np.conj(conjj)
print(con)
ang=np.array([31,50.5555,22/7])
print(np.angle(ang,deg=True))

con=np.concatenate((a,b))#concatenate add without real additon or join
print(con)

[ 7  9  8  8 13 17]
[-5 -5  0  4  1 -1]
[ 6 14 16 12 42 72]
[0.16666667 0.28571429 1.         3.         1.16666667 0.88888889]
[ 1  4 16 36 49 64]
[0 0 0 1]
[0 0 0 1]
[12.+4.j]
[0. 0. 0.]
[1 2 4 6 7 8 6 7 4 2 6 9]


In [71]:
#Random number in matrix
ss=np.random.randint(1,5,dtype=int,size=(2,2))
#(start,end,numberof_values,dtype,size=(row,column))
print(ss)
#it is used to genrating random value 

[[1 3]
 [2 4]]


In [55]:
help(np.linspace)


Help on function linspace in module numpy:

linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
    Return evenly spaced numbers over a specified interval.
    
    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].
    
    The endpoint of the interval can optionally be excluded.
    
    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.
    
    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``
    
    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1``
        evenly spaced samples, so that 

In [64]:
help(np.random.randint)


Help on built-in function randint:

randint(...) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)
    
    Return random integers from `low` (inclusive) to `high` (exclusive).
    
    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).
    
    .. note::
        New code should use the ``integers`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, one above the largest (signed) integer to be drawn
        from the distributi

In [124]:
#Math function with numpy
#there are many math functio
#first trogonometric function
pi=np.pi
print(pi*7)
#this genrates us pi value 
sin=np.sin(324)
cos=np.cos(120)
tan=np.tan(450)
print(sin)
print(cos)
print(tan)
q=np.pi/180
print(np.sin(q))


#tan-1(180) which means inverse value using numpy
aa=np.tan(60)
print(aa)
bb=np.arctan(aa)
print(np.degrees(bb))

#lets do project
ang=np.array([0,30,45,60,90])
sin=np.sin(ang*np.pi/180)
c=np.arcsin(sin)
print(np.degrees(c))

#Now around() , ceil(), floor()
dd=np.array([2.335,-3.234,4.5,4])
print(np.ceil(dd))#ceil return gretaer value than original and equal to original

print(np.floor(dd))#floor return less value than original and equal to original
print(np.around(dd))
print(np.around(dd,decimals=2))#ddecimals defined how number to show in decimal

az=np.array([16,25,100,360,36])
print(np.sqrt(az))#it return square root value

21.991148575128552
-0.4040652194563607
0.8141809705265618
0.9358090133927123
0.01745240643728351
0.320040389379563
17.746770784939255
[ 0. 30. 45. 60. 90.]
[ 3. -3.  5.  4.]
[ 2. -4.  4.  4.]
[ 2. -3.  4.  4.]
[ 2.34 -3.23  4.5   4.  ]
[ 4.          5.         10.         18.97366596  6.        ]


In [103]:
#Now we are going going to learn about Set in numpy
# it is simple mathmatics to find the intersect and common 
a=np.array([1,2,3,4,6,7,8])
b=np.array([6,4,5,2,1,3,4])
intt=np.intersect1d(a,b)#it gives us common value
print(intt)
aa=np.array([
    [1,2,3],
    [6,4,1],
    [6,7,8],
])

bb=np.array([
    [3,2,1],
    [6,7,8],
    [9,0,9],
])

intt1=np.intersect1d(aa,bb)
print(intt1)
# we both case use 1d 


x=np.setdiff1d(a,b)
print(x)#it gives us non-common as a output or diffeences among them


[1 2 3 4 6]
[1 2 3 6 7 8]
[7 8]


In [119]:
#let's use sorting method 
#sorting means simply arranging the number or string
a=np.array([3,2,4,5,1],dtype=int)
print(np.sort(a))
b=np.array(['b','d','a','c'],dtype=str)
print(np.sort(b))
#we can sort both string and number 

#now sorting 2d matrix

two=np.array([
    [7,6,5],
    [1,3,2],
    [3,5,8],
])
print(np.sort(two))

# lets gives to axis 1 means row o means column
print(np.sort(two,axis=1))#sorting row wise
print(np.sort(two,axis=0))#sorting column wise

#lets reverse the matrix

rev=np.flip(two,axis=0)
print(rev)#flip() function used to reverse the value 


[1 2 3 4 5]
['a' 'b' 'c' 'd']
[[5 6 7]
 [1 2 3]
 [3 5 8]]
[[5 6 7]
 [1 2 3]
 [3 5 8]]
[[1 3 2]
 [3 5 5]
 [7 6 8]]
[[3 5 8]
 [1 3 2]
 [7 6 5]]


In [121]:
#Minimum and maximum of array
a=np.array([100,233,44,32,2,1])
print(np.max(a))
print(np.min(a))
print(np.size(a))#size is used as len


233
1
6


In [28]:
#Indexing and slicing 
import numpy as np
a=np.array([1,2,3,4,5,6,7])
#lets index the 1d array
print(a[2],a[0])

b=np.array([
    [3,4,5,6,6],
    [7,8,9,0,5],
])
print(b[1][4])
#indexing 2d array
print(b[0:])#it will start from 0 and cover all
print(b[1:])#it will print only one becuase there is no other any left 
#now we have done some slicing method 

#multidimensionla aary

x=np.array([
    [
        [1,2,3,4],
        [4,5,6,7],
        [8,9,0,1],
    ],
    [
        [3,4,5,6],
        [6,7,8,9],
        [8,9,0,5],
    ]
])

index=x[0][0][0]
print(index)

index2=x[1][0][0]
print(index2)

print(a[0::3])#double dot is step

3 1
5
[[3 4 5 6 6]
 [7 8 9 0 5]]
[[7 8 9 0 5]]
1
3
[1 4 7]


In [46]:
#statistics
#imp
m=np.array([1,2,3,4,45,5,66])
print(np.mean(m))
print(np.median(m))
print(np.std(m))
print(np.average(m))
print(np.var(m))#it is variance



18.0
4.0
24.40140511176706
18.0
595.4285714285714
0.0


In [52]:
#let's find the determinant of matrix
i=np.array([
    [3,2],
    [5,6]
])
s=round(np.linalg.det(i))#using round to avoid decimal
print(s)
#abs() function gives us absolute value

#let's find the inverse of matrix
print(np.linalg.inv(i))

8.000000000000002
[[ 0.75  -0.25 ]
 [-0.625  0.375]]


In [48]:
#linear algebra
x1=int(input("enter value of x1: "))
y1=int(input("enter value of y1: "))
x2=int(input("enter value of x2: "))
y2=int(input("enter value of y2: "))
c1=int(input("enter conatant value: "))
c2=int(input("enter constant value: "))
a=np.array([
    [x1,y1],
    [x2,y2],
])#its equation breakdown
b=np.array([c1,c2])#it's constant
s=np.linalg.solve(x,b)
print("the value x and y:",s)

enter value of x1: 1
enter value of y1: 1
enter value of x2: 1
enter value of y2: -1
enter conatant value: 4
enter constant value: 3
the value x and y: [1.11111111 1.44444444]


In [39]:
#stack
a=np.array([
    [1,2,3,4],
    [4,5,6,7]
])
xx=np.column_stack((a))#it takes argument as tuple
print(xx)#it print as a colimn

xy=np.row_stack((a))#row stack is used to print row only
print(xy)
h=np.hstack((a))
print(h)#print horizontally
hg=np.vstack((a))#print vertically
print(hg)


[[1 4]
 [2 5]
 [3 6]
 [4 7]]
[[1 2 3 4]
 [4 5 6 7]]
[1 2 3 4 4 5 6 7]
[[1 2 3 4]
 [4 5 6 7]]


In [31]:
#Io with numpy
import numpy as np
# aa=np.array([1,2,3,4,5,6,7])
# np.save("safal",aa)#it automatically saves with with numpy extension
#or we can save as txt also
#Now load save file to seee
p=np.load("safal.npy")
print(p)

[1 2 3 4 5 6 7]
